service:
  activeExample: NachaFile
  batchOrderExecutor.fixedRate: 30000

server:
  port: 9915

# Service registry client configuration for local execution
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
#    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

backbase.batches.nacha.writer:
  defaultFormat: true
  settings:
    immediateDestinationCode: 999999999
    immediateDestinationName: Immediator